# Site settings
title: Jobalia's GitHub Pages
email: sjobalia@stanford.edu
description: > # This means to ignore newlines until "baseurl:"
  A brief description of your GitHub Pages site.
baseurl: "" # The subpath of your site, e.g. /blog/
url: "http://jobalias.github.io" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal  # Or any other supported Jekyll theme
